name: "basic-network"

version: 1.0.0

client:
  organization: Org1
  logging:
    level: info

channels:
  mychannel:
    orderers:
      - orderer.example.com
    peers:
      peer0.org1.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true
      peer0.org2.example.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

organizations:
  OrdererOrg:
    mspID: OrdererMSP
    cryptoPath: crypto-config/ordererOrganizations/example.com/users/Admin@example.com/msp
    orderers:
      - orderer.example.com

  Org1:
    mspID: Org1MSP
    cryptoPath: crypto-config/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
    peers:
      - peer0.org1.example.com

  Org2:
    mspID: Org2MSP
    cryptoPath: crypto-config/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp
    peers:
      - peer0.org2.example.com

orderers:
  orderer.example.com:
    url: grpc://localhost:7050

peers:
  peer0.org1.example.com:
    url: grpc://localhost:7051

  peer0.org2.example.com:
    url: grpc://localhost:8051

certificateAuthorities:
  ca.org1.example.com:
    url: http://localhost:7054
    caName: ca-org1

  ca.org2.example.com:
    url: http://localhost:8054
    caName: ca-org2