Organizations:
  - &OrdererOrg
    Name: OrdererOrg
    ID: OrdererMSP
    MSPDir: crypto-config/ordererOrganizations/example.com/msp
    Policies:
        Readers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
        Writers:
            Type: Signature
            Rule: "OR('OrdererMSP.member')"
        Admins:
            Type: Signature
            Rule: "OR('OrdererMSP.admin')"
    OrdererEndpoints:
        - orderer.example.com:7050
            

  - &Org1
      Name: Org1MSP
      ID: Org1MSP
      MSPDir: crypto-config/peerOrganizations/org1.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
          Writers:
              Type: Signature
              Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
          Admins:
              Type: Signature
              Rule: "OR('Org1MSP.admin', 'Org2MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer', 'Org1MSP.admin', 'Org2MSP.admin')"
      AnchorPeers:
          - Host: peer0.org1.example.com
            Port: 7051

  - &Org2
      Name: Org2MSP
      ID: Org2MSP
      MSPDir: crypto-config/peerOrganizations/org2.example.com/msp
      Policies:
          Readers:
              Type: Signature
              Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
          Writers:
              Type: Signature
              Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
          Admins:
              Type: Signature
              Rule: "OR('Org2MSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('Org1MSP.member', 'Org2MSP.member', 'Org1MSP.peer', 'Org2MSP.peer')"
      AnchorPeers:
          - Host: peer0.org2.example.com
            Port: 9051

Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true

    Orderer: &OrdererCapabilities
        V2_0: true

    Application: &ApplicationCapabilities
        V2_0: true


Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities


Orderer: &OrdererDefaults
    OrdererType: solo
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

        
Application: &ApplicationDefaults
    Organizations:
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Endorsement"
    Capabilities:
        <<: *ApplicationCapabilities

Profiles:
  TwoOrgsOrdererGenesis:
    <<: *ChannelDefaults
    Orderer:
        <<: *OrdererDefaults
        Organizations:
            - *OrdererOrg
    Consortiums:
        SampleConsortium:
            Organizations:
                - *Org1
                - *Org2

  TwoOrgsChannel:
      <<: *ChannelDefaults
      Consortium: SampleConsortium
      Application:
          <<: *ApplicationDefaults
          Organizations:
              - *Org1
              - *Org2
          Capabilities:
              <<: *ApplicationCapabilities